# Generated by Django 4.0.3 on 2022-03-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='reader',
        ),
        migrations.AddField(
            model_name='meeting',
            name='readers',
            field=models.ManyToManyField(related_name='attending', to='bookclubapi.reader'),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='book',
        ),
        migrations.AddField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='bookclubapi.book'),
            preserve_default=False,
        ),
    ]
