# Generated by Django 4.0.3 on 2022-03-21 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapi', '0003_meeting_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='selector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choosing', to='bookclubapi.reader'),
        ),
    ]
